import type { Metadata } from "next";
import { Italiana, Tangerine } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const helvetica = localFont({
  src: "./Helvetica/Helvetica.ttf",
  variable: "--font-helvetica",
  display: "swap",
});

const helveticaBold = localFont({
  src: "./Helvetica/Helvetica-Bold.ttf",
  variable: "--font-helvetica-bold",
  display: "swap",
});

const italiana = Italiana({
  variable: "--font-italiana",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

const tangerine = Tangerine({
  variable: "--font-tangerine",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${italiana.variable} ${helvetica.variable} ${helveticaBold.variable} ${italiana.variable} ${tangerine.variable} relative antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
